### ISSUE TITLE
While running on camera.js i got this error uncaughtException { Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by sarankani** [moeiscool/Shinobi#148]
uncaughtException { Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs:
   [ '-loglevel',
     'quiet',
     '-i',
     'http://came3.nkansai.ne.jp:81/nphMotionJpeg?Resolution=640x480&Quality=Motion',
     '-s',
     '400x400',
     '-r',
     '25',
     '-ss',
     '1.8',
     '-frames:v',
     '1',
     '-f',
     'singlejpeg',
     'pipe:1' ] }

**Comment by moeiscool** [comment]
Looks like you are missing FFMPEG.

Follow the first 6 steps of "Ubuntu 16.04 : The Harder Way, Dont have FFMPEG installed?" http://shinobi.video/docs/start#setup_ubuntu_hard

This will get you FFMPEG 3.x
