### ISSUE TITLE
camera.js line 264, undefined s.dir.buffer, TypeError exception

### ISSUE THREAD

**Issue by DL44227** [moeiscool/Shinobi#212]
camera.js in todays dev branch is throwing the following exception on start:

uncaughtException TypeError: path must be a string or Buffer
    at Object.fs.mkdirSync (fs.js:877:18)
    at Object.<anonymous> (/opt/shinobi-dev-20170630/camera.js:265:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

I have added a console.log output just before and find out, that s.dir.buffer=undefined

**Comment by moeiscool** [comment]
Fixed in newest dev. Thx!
